"""Write ../coverage.js: how often the model saw each spelling of the words that
have topic cues, counted over unique training sentences.

The engine trusts the model wherever it had data, and lets a topic cue decide
only where it provably did not: plural "Bußen" occurs 4 times in the training
data, so the model's opinion of it is a prior, not evidence. On held-out text
the cues are otherwise less reliable than the model (cues_vs_model.py).
"""
import json, re
from pathlib import Path

HERE = Path(__file__).parent
WORD = re.compile(r"\w*(?:ss|ß)\w*")


def cue_forms():
    src = (HERE.parent / "dictionary.js").read_text(encoding="utf-8")
    block = src[src.index("ssCues: {"):src.index("\n  },", src.index("ssCues: {"))]
    return {k for keys in re.findall(r"'([^']+)': \{", block) for k in keys.split(",")}


def main():
    forms = cue_forms()
    counts = {f: [0, 0] for f in forms}
    seen = set()
    with open(HERE / "data" / "train.jsonl", encoding="utf-8") as fh:
        for line in fh:
            german = json.loads(line)["german"]
            if german in seen:          # balancing repeats sentences; count each once
                continue
            seen.add(german)
            for w in WORD.findall(german):
                form = w.replace("ß", "ss").lower()
                if form in counts:
                    counts[form][1 if "ß" in w else 0] += 1
    body = json.dumps(dict(sorted(counts.items())), ensure_ascii=False)
    (HERE.parent / "coverage.js").write_text(
        "// Generated by training/coverage.py. How often the eszett model saw each\n"
        "// spelling of the words that have topic cues, as [ss, ß] over unique\n"
        "// training sentences. Where a spelling was nearly absent, the model's\n"
        "// opinion of it is a prior rather than evidence, and the cue decides.\n"
        f"globalThis.HD_COVERAGE = {body};\n", encoding="utf-8")
    print("coverage.js:", body)


if __name__ == "__main__":
    main()
