"""Which dictionary words are also ordinary German? Writes ../german_too.js.

"Rande" is Swiss for beetroot and German for edge ("am Rande"), "Store" is a
Swiss blind and a German shop, "Estrich" a Swiss attic and a German floor screed.
Rewriting them everywhere turns "am Rande des Estrichs" into "am Rote Bete des
Dachbodens". So for these words the rules' rewrite becomes a choice, and the
general language model may keep the original where it reads clearly better in
its sentence.

Which words those are comes from the web crawl (names_extract.py), not from a
list: a form counts as also German when, per page, it is less than SWISS_RATIO
times as common on .ch pages as on .de pages, with at least MIN_DE occurrences
on .de pages.
"""
import json
from pathlib import Path

HERE = Path(__file__).parent
SWISS_RATIO = 5          # the same line names_eval.py draws
MIN_DE = 20


def main():
    c = json.loads((HERE / "data" / "names" / "counts.json").read_text(encoding="utf-8"))
    pages, words = c["pages"], c["words"]
    rate = lambda side, k: words[side].get(k, 0) / pages[side]
    also = sorted(k for k in set(words["de"]) | set(words["ch"])
                  if k[:1].isupper()                              # compound heads are not words
                  and words["de"].get(k, 0) >= MIN_DE
                  and rate("ch", k) < SWISS_RATIO * rate("de", k))
    body = json.dumps(also, ensure_ascii=False)
    (HERE.parent / "german_too.js").write_text(
        "// Generated by training/german_too.py from a German web crawl: dictionary words\n"
        "// that are also ordinary German, where the language model may keep the original.\n"
        f"globalThis.HD_GERMAN_TOO = {body};\n", encoding="utf-8")
    print(len(also), also)


if __name__ == "__main__":
    main()
